config/routes.rb
CatarseStripe::Engine.routes.draw do
  namespace :payment do
    get '/stripe/:id/review' => 'stripe#review', :as => 'review_stripe'
    post '/stripe/notifications' => 'stripe#ipn',  :as => 'ipn_stripe'
    match '/stripe/callback'          => 'stripe#callback',       :as => 'stripe_auth_callback'
    match '/stripe/:id/notifications' => 'stripe#notifications',  :as => 'notifications_stripe'
    match '/stripe/:id/pay'           => 'stripe#pay',            :as => 'pay_stripe'
    match '/stripe/:id/success'       => 'stripe#success',        :as => 'success_stripe'
    match '/stripe/:id/cancel'        => 'stripe#cancel',         :as => 'cancel_stripe'
    match '/stripe/:id/charge'        => 'stripe#charge',         :as => 'charge_stripe'
    match '/stripe/auth'              => 'stripe#auth',           :as => 'stripe_auth'
  end
end

app/controllers/catarse_stripe/payment/application_controller.rb
module CatarseStripe::Payment
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/catarse_stripe/payment/stripe_controller.rb
require 'catarse_stripe/processors'
require 'json'
require 'stripe'
require 'oauth2'

module CatarseStripe::Payment
    class StripeController < ApplicationController
    
    skip_before_filter :verify_authenticity_token, :only => [:notifications]
    skip_before_filter :detect_locale, :only => [:notifications, :connect]
    skip_before_filter :set_locale, :only => [:notifications, :connect]
    skip_before_filter :force_http

    before_filter :setup_auth_gateway

    SCOPE = "projects.backers.checkout"
    AUTH_SCOPE = "users.auth"

    layout :false

    #Makes the call to @client.auth_code.authorize_url from auth.html.erg
    def auth
      @stripe_user = current_user
      respond_to do |format|
        format.html
        format.js
      end
    end

    #Brings back the authcode from Stripe and makes another call to Stripe to convert to a authtoken
    def callback
      @stripe_user = current_user
      code = params[:code]

      @response = @client.auth_code.get_token(code, {
      :headers => {'Authorization' => "Bearer #{::Configuration['stripe_secret_key']}"} #Platform Secret Key
      })
      
      #Save PROJECT owner's new keys
      @stripe_user.stripe_access_token = @response.token
      @stripe_user.stripe_key = @response.params['stripe_publishable_key']
      @stripe_user.stripe_userid = @response.params['stripe_user_id']
      @stripe_user.save

      
      return redirect_to payment_stripe_auth_path
    rescue Stripe::AuthenticationError => e
      ::Airbrake.notify({ :error_class => "Stripe #Pay Error", :error_message => "Stripe #Pay Error: #{e.inspect}", :parameters => params}) rescue nil
      Rails.logger.info "-----> #{e.inspect}"
      flash[:error] = e.message
      return redirect_to main_app.user_path(@stripe_user)
    end

    def review
    
    end

    def ipn
      #return render status: 200, nothing: true if (details.livemode == false && Rails.env.production? == true)
      stripe_key = User.find_by_stripe_userid(params[:user_id]).stripe_access_token
      details = Stripe::Event.retrieve(params[:id], stripe_key)
      if details.type == "charge.succeeded"
        confirm_backer(details,stripe_key)
      elsif details.type == "charge.refunded"
        refund_backer(details, stripe_key)
      end
      return render status: 200, nothing: true
    rescue Stripe::CardError => e
      ::Airbrake.notify({ :error_class => "Stripe Notification Error", :error_message => "Stripe Notification Error: #{e.inspect}", :parameters => params}) rescue nil
      return render status: 200, nothing: true
    end

    def confirm_backer(details, stripe_key)
      charge = details.data.object
      customer = Stripe::Customer.retrieve(charge.customer, stripe_key)
      backer = Backer.where(:payment_id => charge.id).first
      if backer
        notification = backer.payment_notifications.new({
          extra_data: customer.email
        })
        notification.save!
        backer.update_attribute(:payment_service_fee, (charge.amount * ::Configuration['catarse_fee'].to_f) / 100 )
        if charge.paid == true
          backer.confirm!
        end
      end
    end

    def refund_backer(details)
      charge = details.data.object
      backer = Backer.where(:payment_id => charge.id).first
      if backer
        backer.refund! if !backer.refunded?
      end
    end

    def notifications
      backer = Backer.find params[:id]
      details = Stripe::Charge.retrieve(
          id: backer.payment_id
          )
      if details.paid = true
        build_notification(backer, details)
        render status: 200, nothing: true
      else
        render status: 404, nothing: true
      end
    rescue Stripe::CardError => e
      ::Airbrake.notify({ :error_class => "Stripe Notification Error", :error_message => "Stripe Notification Error: #{e.inspect}", :parameters => params}) rescue nil
      render status: 404, nothing: true
    end
    
    def charge
      @backer = current_user.backs.find params[:id]
      access_token = @backer.project.stripe_access_token #Project Owner SECRET KEY

      respond_to do |format|
        format.html
        format.js
      end
    end 

    def pay
      @backer = current_user.backs.find params[:id]
      access_token = @backer.project.stripe_access_token #Project Owner SECRET KEY
      begin
        customer = Stripe::Customer.create(
        {
           email: @backer.payer_email,
           card: params[:stripeToken]
           },
        access_token
        )
        
        @backer.update_attributes(:payment_token => customer.id)
        @backer.save
        flash[:notice] = "Stripe Customer ID Saved!"

        response = Stripe::Charge.create(
          {
          customer: @backer.payment_token,
          amount: @backer.price_in_cents,
          currency: 'usd',
          description: t('stripe_description', scope: SCOPE, :project_name => @backer.project.name, :value => @backer.display_value),
          application_fee: (@backer.price_in_cents * ::Configuration['catarse_fee'].to_f).to_i
          },
          access_token #ACCESS_TOKEN (Stripe Secret Key of Connected Project Owner NOT platform)
        )

        @backer.update_attributes({
          :payment_method => 'Stripe',
          :payment_token => response.customer, #Stripe Backer Customer_id
          :payment_id => response.id, #Stripe Backer Payment Id
          :confirmed => response.paid #Paid = True, Confirmed =  true
        })
        @backer.save

        build_notification(@backer, response)
      
        redirect_to payment_success_stripe_url(id: @backer.id)
      rescue Stripe::CardError => e
        ::Airbrake.notify({ :error_class => "Stripe #Pay Error", :error_message => "Stripe #Pay Error: #{e.inspect}", :parameters => params}) rescue nil
        Rails.logger.info "-----> #{e.inspect}"
        flash[:error] = e.message
        return redirect_to main_app.new_project_backer_path(@backer.project)
      end
    end

    def success
      backer = current_user.backs.find params[:id]
      access_token = backer.project.stripe_access_token #Project Owner SECRET KEY
      begin
        details = Stripe::Charge.retrieve(
        {
          id: backer.payment_id
          },
          access_token
          )

        build_notification(backer, details)

        if details.id
          backer.update_attribute :payment_id, details.id
        end
        stripe_flash_success
        redirect_to main_app.project_backer_path(project_id: backer.project.id, id: backer.id)
      rescue Stripe::CardError => e
        ::Airbrake.notify({ :error_class => "Stripe Error", :error_message => "Stripe Error: #{e.message}", :parameters => params}) rescue nil
        Rails.logger.info "-----> #{e.inspect}"
        flash[:error] = e.message
        return redirect_to main_app.new_project_backer_path(backer.project)
      end
    end

    def cancel
      backer = current_user.backs.find params[:id]
      flash[:failure] = t('stripe_cancel', scope: SCOPE)
      redirect_to main_app.new_project_backer_path(backer.project)
    end

  private
    #Setup the Oauth2 Stripe call with needed params - See initializers.stripe..rb..the Stripe keys are setup in the seed.db or added manually with a Configuration.create! call.
    def setup_auth_gateway
      session[:oauth] ||= {}

      @client = OAuth2::Client.new((::Configuration['stripe_client_id']), (::Configuration['stripe_access_token']), {
        :site => 'https://connect.stripe.com',
        :authorize_url => '/oauth/authorize',
        :token_url => '/oauth/token'
      })
    end

    def build_notification(backer, data)
      processor = CatarseStripe::Processors::Stripe.new
      processor.process!(backer, data)
    end

    def stripe_flash_error
      flash[:failure] = t('stripe_error', scope: SCOPE)
    end

    def stripe_flash_success
      flash[:success] = t('success', scope: SCOPE)
    end

    def stripe_auth_flash_error
      flash[:failure] = t('stripe_error', scope: AUTH_SCOPE)
    end

    def stripe_auth_flash_success
      flash[:success] = t('success', scope: AUTH_SCOPE)
    end
  end
end

app/views/catarse_stripe/payment/stripe/auth.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stripe Connect</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css" rel="stylesheet">
    <style>
    body{background-color: #e5e5e5;}
    div.container { position: relative;}
    div.row { position: absolute; margin:30px 50px 50px 50px;}
    div.stripe-field { 
        position:absolute; 
        left: 0; 
        right: 0; 
        margin-left: auto; 
        margin-right: auto;
        }
    div.stripe-field .stripe-connect-btn { text-align: left;}
    </style>
  </head>
  <body>
	   <div class="container">
		    <div class="row">
		      <div class="span4">
		        <div class="stripe-field">
		          <h2>Stripe Connect</h2>
                    <% if current_user.stripe_access_token %>
                        <h4>STRIPE CONNECTED!</h4>
                        <p> You are ready to receive payments for your projects!</p>
                        <p>Your Stripe user ID: <%= current_user.stripe_userid %></p>
                    <% else %>
        		        <p> In order to use Stripe payments as your payment processor, you'll need to connect and create a Stripe account. You can do that easily through this Crowdfunding platform.</p>
                        <p> If you don't have a Stripe account, you'll be prompted to create one</p>
                        <p class="stripe-connect-btn">
                            <a href="<%= @client.auth_code.authorize_url(:scope => 'read_write', :stripe_landing => 'register') %>">
                                <img src="/assets/catarse_stripe/auth/stripe_blue.png">
                            </a>
                        </p>
                    <% end %>
                    <p><%= link_to "Back To User", main_app.user_path(@stripe_user), :class => "btn btn-primary" %></p>
				</stripe-field>
				<script src="http://code.jquery.com/jquery.js"></script>
				<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/js/bootstrap.min.js"></script>
			    </div>
		    </div>
	   </div>
  </body>
</html>

app/views/catarse_stripe/payment/stripe/charge.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stripe Payment</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css" rel="stylesheet">
    <style>
    body{background-color: #e5e5e5;}
    div.container { position: relative;}
    div.row { position: absolute; margin:30px 50px 50px 50px;}
    div.stripe-field { 
        position:absolute; 
        left: 0; 
        right: 0; 
        margin-left: auto; 
        margin-right: auto;
        }
    </style>
  </head>
  <body>
	   <div class="container">
		    <div class="row">
		      <div class="span4">
		        <div class="stripe-field">
		        <h2>Crowdfunding Payments with Stripe</h2>
		        <p>You've chosen to contribute using a credit card. Stripe payments for customers in US and Canada allow you to use your Visa, Mastercard or Amex. Credit Card information is not stored on the crowdfunding website, and is safely stored on Stripe's servers. For more info visit <a href="http://stripe.com"><b>STRIPE PAYMENTS</b></a></p>
				    <%= form_tag payment_pay_stripe_path(params[:id]) do %>
						  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button" data-key="<%= @backer.project.stripe_key %>" data-label="Contribute With Stripe"></script>
						<% end %>
						</stripe-field>
				    <script src="http://code.jquery.com/jquery.js"></script>
				    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/js/bootstrap.min.js"></script>
			    </div>
		    </div>
	   </div>
  </body>
</html>

app/views/catarse_stripe/payment/stripe/charge.html.slim
doctype
html
  head
    title Stripe Payment
    meta content="width=(device-width,)initial-scale=1.0" name="viewport"
    /! Bootstrap
    link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css" rel="stylesheet"
    css:
      | body{background-color: #e5e5e5;}
      | div.container { position: relative;}
      | div.row { position: absolute; margin:50px;}
      | div.stripe-field {
          | position:absolute;
          | left: 0;
          | right: 0;
          | margin-left: auto;
          | margin-right: auto;
          | }
  body
    .container
      .row
        .span4
          .stripe-field
            h2 Crowdfunding Payments with Stripe
            p
              | You've chosen to contribute using a credit card. Stripe payments for customers in US and Canada allow you to use your Visa, Mastercard or Amex. Credit Card information is not stored on the crowdfunding website, and is safely stored on Stripe's servers. For more info visit
              a href="http://stripe.com"
                b STRIPE PAYMENTS
            = form_tag payment_pay_stripe_path(params[:id]) do
              script.stripe-button data-key="<%= @backer.project.stripe_key %>" data-label="Contribute With Stripe" src="https://checkout.stripe.com/v2/checkout.js"
            script src="http://code.jquery.com/jquery.js"
            script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/js/bootstrap.min.js"

app/views/catarse_stripe/payment/stripe/checkout.html.erb
<!-- Button to trigger modal -->
<a href="#donateModal" role="button" class="btn" data-toggle="modal">Click to Donate</a>
 
<div id="donateModal" class="modal hide" role="dialog">
    <form action="#{payment_pay_stripe_path}" method="post" class="form-horizontal">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Donate Form</h3>
      </div>
      <div class="modal-body">
      <div class="control-group">
        <label class="control-label" for="first-name">First Name</label>
        <div class="controls">
          <input id="first-name" name="first-name" type="text" reqired autocomplete="name" />
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="last-name">Last Name</label>
        <div class="controls">
          <input id="last-name" name="last-name" type="text" reqired x-autocompletetype="name-full" />
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="email">Email</label>
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on"><i class="icon-envelope"></i></span><input id="email" name="email" type="email" reqired x-autocompletetype="email" />
          </div>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="amount">Donation Amount</label>
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on">$</span><input id="amount" name="amount" type="number" class="input-mini" />
          </div>
        </div>
      </div>


      <div class="control-group">
        <label class="control-label" for="card">Payment Information</label>
        <div class="controls" id="stripe-button-holder">
          <!-- Stripe Button -->
          <script src="https://button.stripe.com/v1/button.js" class="stripe-button"
            data-key="pk_0TofLEX9n7baBwirc2xo1dHtDm8e0"
            data-label="Add Card"
            data-panel-label="Save"
          ></script>
        </div>
      </div>


      <div class="control-group">
        <label class="control-label" for="anonymous">Privacy</label>
        <div class="controls">
          <label class="checkbox" rel="popover" data-placement="top" data-content="Tick this box and we will not show your name in the list of pledgers" title="Anonymous Donation">
            <input id="anonymous" name="anonymous" type="checkbox" />
            Keep my donation anonymous
          </label>
        </div>
      </div>

      <div class="control-group">
        <div class="controls">
          <label class="checkbox">
            <input id="tos-agreed" name="tos-agreed" type="checkbox" required />
            I Agree to the <a href="#tos-modal" data-toggle="modal">Terms of Service</a>
          </label>
        </div>
      </div>

      <fieldset>
        <legend class="s1">Optional Information</legend>
        <div></div>

        <div class="control-group">
          <label class="control-label" for="company">Company</label>
          <div class="controls">
            <input id="company" name="company" type="text" x-autocompletetype="organization" />
          </div>
        </div>


        <div class="control-group">
          <label class="control-label" for="website">Website</label>
          <div class="controls">
            <div class="input-prepend">
              <span class="add-on"><i class="icon-globe"></i></span><input id="website" name="website" type="url" x-autocompletetype="url" />
            </div>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label" for="phone">Phone</label>
          <div class="controls">
            <div class="input-prepend">
              <span class="add-on"><i class="icon-phone"></i></span><input id="phone" name="phone" type="tel" class="input-medium" x-autocompletetype="phone-full" />
            </div>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label" for="referrer"><small>How did you hear about us?</small></label>
          <div class="controls">
            <input id="referrer" name="referrer" type="text" placeholder="Google, Friend..." />
          </div>
        </div>

          <div class="control-group">
          <label class="control-label" for="notes">Notes / Comments</label>
          <div class="controls">
            <textarea id="notes" name="notes" placeholder="Any message you may have for us." class="input-xlarge" rows="2"></textarea>
          </div>
        </div>


      </fieldset>
      </div>
    <div class="modal-footer">
      <div class="pull-right">
        <button class="btn btn-success btn-large">Send Pledge</button>
      </div>
    </div>
    </form>
</div>

app/views/catarse_stripe/payment/stripe/review.html.slim
= javascript_include_tag 'catarse_stripe'

h3= t('projects.backers.review.international.section_title')

#catarse_stripe_form
  = form_tag payment_charge_stripe_path(params[:id]) do
    .clearfix
    .bootstrap-twitter
      = submit_tag t('projects.backers.review.international.button'), :class => 'btn btn-primary btn-large'